### ISSUE TITLE
   1.4.5版本 评论区和动态不显示，成功了一次

### ISSUE THREAD

**Issue by YRu97** [MaxChang3/Bilibili-Web-Show-IP-Address#4]
1.4.5版本 评论区和动态不显示，成功了一次 刷新网页 或者换个视频 就不显示了，win10 x64    edge   114.0.1823.58 (正式版本) (64 位)  降级回1.4.4 评论区和动态可以正常显示
![1 4 4](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/8189a791-c4eb-48e3-9957-15e707a2c78c)
![1 4 55](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/62426ace-b350-46a1-bf6a-f728a13fe9f2)
![1 4 5](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/517b8b46-cae3-46d0-b920-d1d9668a2fda)

**Comment by YRu97** [comment]
![KLR7@7@6AGUIPDW _V99U`6](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/5460e237-9a5d-4217-864b-7d4f4e0c1d3e)

**Comment by YRu97** [comment]
第一张评论区显示了ip的是1.4.4版本的

**Comment by MaxChang3** [comment]
1.4.5 重写了一下从主页进入动态的逻辑和添加了元素选择的超时机制，可能和这个有关。明天我看看。请问控制台有报错吗？

**Comment by YRu97** [comment]
控制台在哪里a  视频链接吗？

**Comment by MaxChang3** [comment]
> 控制台在哪里a  视频链接吗？

F12 后选择 console（控制台）

或者 设置 - 更多工具 -开发者工具。

是的，视频链接和动态链接。

**Comment by YRu97** [comment]
![7{QZ{5Z@L3MW%VFKY5}%(RH](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/d6026e25-7580-4697-be84-87bad381ece3)

**Comment by YRu97** [comment]
![G~Z$GFAS_@B(41} W}5}H5H](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/b3f69942-1b5b-4128-aec8-340a5f7d7d9e)

**Comment by YRu97** [comment]
https://www.bilibili.com/video/BV1aj411D7tL/?spm_id_from=333.1007.tianma.2-3-6.click&vd_source=852188400c185669b3f238c50ec3d305

**Comment by YRu97** [comment]
https://space.bilibili.com/350882304/dynamic

**Comment by YRu97** [comment]
https://www.bilibili.com/video/BV1rk4y1M7Rj/?spm_id_from=333.788.top_right_bar_window_history.content.click&vd_source=852188400c185669b3f238c50ec3d305

**Comment by MaxChang3** [comment]
似乎没有相关报错，明早我排查下问题在哪里～暂时先使用先前的版本吧🙏

**Comment by YRu97** [comment]
![~7I6`WQAP%H0)3SRVQMT3)U](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/2b52e38a-6402-499c-b2bc-80c59a8c735f)
![14XS1X6YFEF}H4_~28`B3(S](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/50d17597-4a93-427a-a576-58387c62e0ab)

**Comment by YRu97** [comment]
1.4.4 版本控制台 辛苦了

**Comment by MaxChang3** [comment]
好像就是超时机制的问题，我升级后确实也如此。但是仅在视频评论区，动态似乎没问题。

压缩包中一个是增加了时限长度的版本，一个是去除的，你试试哪个可行？单纯的限制超时时间似乎无法平衡不同网络环境下的速度，不行我还是去掉好了。

[test.zip](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/files/11858840/test.zip)

动态我再看看。

**Comment by YRu97** [comment]
![9M88)(62ERT5$JGPKVF9OVQ](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/cdf17fbe-acf4-4220-96cd-3408074ba474)
![JKP%(ZUAED %UXQR4(2O6`Y](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/d6e67b41-e40a-4333-8e8a-dc83df3b41a3)
无时限的有个动态出现这种情况，
![~7R3}95 L@`K(SP%9ONXD{J](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/fb0f181f-f6c6-451e-94a8-1328bba6f069)
刷新好几次都是这样    ，直接进入对应链接，先进入首页再点开动态都能正常显示

**Comment by YRu97** [comment]
就这个异常，其他视频 动态都可以

**Comment by YRu97** [comment]
我又试了下1.4.5 动态评论区可以正常显示，视频评论区不行

**Comment by YRu97** [comment]
![无时限js](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/9431d135-c56c-43a3-a9e8-52364f466d6b)

**Comment by YRu97** [comment]
无时限的

**Comment by YRu97** [comment]
![无时限js2](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/a4000718-0599-4d3e-92d7-d3b29575ffcf)

**Comment by YRu97** [comment]
无时限的

**Comment by YRu97** [comment]
![无时限3动态](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/ae22f9a8-82db-456d-9255-5ee33c5116d0)
无时限动态

**Comment by YRu97** [comment]
> ![9M88)(62ERT5$JGPKVF9OVQ](https://user-images.githubusercontent.com/92353453/248533768-cdf17fbe-acf4-4220-96cd-3408074ba474.png) ![JKP%(ZUAED %UXQR4(2O6Y](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/d6e67b41-e40a-4333-8e8a-dc83df3b41a3) 无时限的有个动态出现这种情况， ![~7R3}95 L@K(SP%9ONXD{J](https://user-images.githubusercontent.com/92353453/248534158-fb0f181f-f6c6-451e-94a8-1328bba6f069.png) 刷新好几次都是这样 ，直接进入对应链接，先进入首页再点开动态都能正常显示

https://space.bilibili.com/393909408/dynamic

**Comment by YRu97** [comment]
![J5HG``U 0K8IS@J_D 3W{)B](https://github.com/MaxChang3/Bilibili-Web-Show-IP-Address/assets/92353453/1f14cece-4cc0-46c0-ad41-3f08e5fb5e08)
zhe'g这个动态评论区显示异常，这个up其他动态正常显示

**Comment by MaxChang3** [comment]
20 年还没有开放 IP 属地，所以这个没有数据，我后面判断一下显示未知好了。

**Comment by YRu97** [comment]
原来如此，对  有时限的还在试

**Comment by YRu97** [comment]
有时限的除了20年的    正常显示

**Comment by MaxChang3** [comment]
> 有时限的除了20年的 正常显示

OK，那暂时先把时限调高好了~ 感谢！

**Comment by YRu97** [comment]
👍👍👍

**Comment by MaxChang3** [comment]
1.4.6 已经同步，更新即可~

**Comment by YRu97** [comment]
👍
