### ISSUE TITLE
1.4.6 无法显示地址

### ISSUE THREAD

**Issue by mogosan** [maxchang3/Bilibili-Web-Show-IP-Address#8]
t.bilibili.com 和 space.bilibili.com/dynamic 全部失效
视频评论也失效了

**Comment by maxchang3** [comment]
你好，我这边测试下来都正常工作，找了一些其他设备也是，请确定脚本正常开启的情况下，看看有没有插件的相关报错？

**Comment by maxchang3** [comment]
看了下，是 url 的匹配机制导致 `t.bilibili.com/?` 会被判断为单独的动态页，我增加了额外判断，更新 1.4.7 即可。

**Comment by maxchang3** [comment]
有时候网速较慢 / 加载出现问题的时候可能会导致元素检测超时直接报错，这个我再想办法优化一下，比如用 observer 检测一下🤔
